### PR TITLE
Drop -math dependency to workaround Math module name clash

### PR DESCRIPTION
**Pull request by jacereda**

### CODE REVIEW

**Comment by garyb** [comment]
Can you explain what the problem is? This sounds like potentially a compiler problem if you're seeing an error somewhere, as the `Math` module used to work fine in browser and node, despite the overlapping name.

**Comment by jacereda** [comment]
Here is the generated code, I don't know why it works in your case, Math.random is looking up the PS Math module.

    // Generated by psc-make version 0.6.5
    "use strict";
    var Prelude = require("Prelude");
    var Math = require("Math");
    var Control_Monad_Eff = require("Control.Monad.Eff");
    
      function random() {
        return Math.random();
      }
      ;

**Comment by jacereda** [comment]
Might be a node vs io.js issue

**Comment by garyb** [comment]
Oh, oops, I see what you mean, this definitely doesn't work right now...

**Comment by jacereda** [comment]
BTW, Math.random() wasn't the issue, but Math.floor()...

**Pull request closed without merging**
