### PR TITLE
check if global or window

### PR DESCRIPTION
**Pull request by cryogenian**

### CODE REVIEW

**Comment by paf31** [comment]
I don't know how I feel about this issue. It seems like the real solution is to rename the PureScript `Math` module, but that's a breaking change for quite a lot of libraries.

**Comment by cryogenian** [comment]
maybe it should generate <code>var PS_Math = ... </code> from <code>import Math</code> ?

**Comment by paf31** [comment]
Yes, that's another option.

**Comment by garyb** [comment]
I think the latter would be my preferred option (or `$Math`, to match other reserved identifiers). 

Renaming the module doesn't seem like a great solution to me, aside from the dependency issue, as everywhere else we're freeing the user from the JavaScript namespace, so why not here also.

**Comment by paf31** [comment]
Agreed.

**Comment by joneshf** [comment]
For all PS modules?

**Comment by garyb** [comment]
Just clashing ones - this can probably be fixed just by adding `Math` to the `reservedJsIdents` (or whatever it's called) list.

**Comment by garyb** [comment]
I'll sort this out tomorrow - I had wanted to do so tonight, but just didn't get around to it. It's a little trickier than updating `nameIsJsReserved`, but not much.

**Comment by jdegoes** [comment]
It looks like [core-tests](https://github.com/purescript/core-tests/blob/master/src/Test/Math.purs) already tests this, so I'm surprised this happened. Anyway, it wouldn't hurt accepting a quick PR fix for this while the compiler issues are sorted out.

**Comment by garyb** [comment]
Also fixed by purescript/purescript#855 - we've not released this as a new version yet though.

**Pull request closed without merging**
